import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import useSWR from "swr"
import fetcher from "@/utils/fetcher"
import { Entry } from "@prisma/client"

const Entries: NextPage = () => {
  const { data } = useSWR<Entry[]>("/api/entries", fetcher)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    </div>
  )
}

export default Entries
